// Generated by CoffeeScript 1.10.0
(function() {
  var Handshake;

  Handshake = (function() {
    var _connect, _exchange, _leave, reactions, socket;

    socket = null;

    reactions = null;

    function Handshake(configuration, _reactions) {
      var io, signalServer;
      io = configuration.io;
      signalServer = configuration.signalServer;
      socket = io(signalServer);
      reactions = _reactions;
      socket.on('connect', _connect);
      socket.on('exchange', _exchange);
      socket.on('leave', _leave);
    }

    Handshake.prototype.join = function(id, callback) {
      return socket.emit('join', id, (function(_this) {
        return function(socketIds) {
          return callback(null, socketIds);
        };
      })(this));
    };

    Handshake.prototype.leave = function(id, callback) {
      return callback(null, id);
    };

    Handshake.prototype.candidate = function(id, _candidate) {
      return socket.emit('exchange', {
        'to': id,
        'candidate': _candidate
      });
    };

    Handshake.prototype.description = function(id, _description) {
      return socket.emit('exchange', {
        'to': id,
        'sdp': _description
      });
    };

    _connect = function(data) {
      if (reactions.didConnect != null) {
        return reactions.didConnect(data);
      }
    };

    _exchange = function(data) {
      if (reactions.didExchange != null) {
        return reactions.didExchange(data);
      }
    };

    _leave = function(id) {
      if (reactions.didLeave != null) {
        return reactions.didLeave(id);
      }
    };

    return Handshake;

  })();

  module.exports = Handshake;

}).call(this);

//# sourceMappingURL=Handshake.js.map
