// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(express, config) {
    var configStr, router;
    router = express.Router();
    configStr = JSON.stringify(config);
    router.get('/', function(req, res, next) {
      if (req.secure) {
        console.log("SSL REQUEST:");
        res.render('index', {
          title: config.title,
          source: config.cdn,
          config: configStr
        });
      } else {
        console.log("NON-SSL REQUEST");
        res.render('warning', {
          title: config.title,
          config: configStr
        });
      }
    });
    return router;
  };

}).call(this);

//# sourceMappingURL=index.js.map
