// Generated by CoffeeScript 1.10.0
(function() {
  var coffee, coffeeFiles, gulp, gutil, parallelize, path, sourcemaps, tap, threads, touch;

  gulp = require('gulp');

  gutil = require('gulp-util');

  coffee = require('gulp-coffee');

  sourcemaps = require('gulp-sourcemaps');

  touch = require('touch');

  path = require('path');

  tap = require('gulp-tap');

  parallelize = require("concurrent-transform");

  threads = 100;

  coffeeFiles = ['app/**/*.coffee', 'test/**/*.coffee', 'gulfile.coffee', 'app.coffee', 'routes/*.coffee', 'config.coffee'];

  gulp.task('touch', function() {
    return gulp.src(coffeeFiles).pipe(tap(function(file, t) {
      return touch(file.path);
    }));
  });

  gulp.task('coffeescripts', function() {
    return gulp.src(coffeeFiles).pipe(sourcemaps.init()).pipe(parallelize(coffee({
      bare: true
    }).on('error', gutil.log), threads)).pipe(parallelize(sourcemaps.write('./'), threads)).pipe(parallelize(gulp.dest(function(file) {
      return file.base;
    }), threads));
  });

  gulp.task('watch', function() {
    return gulp.watch(coffeeFiles, ['coffeescripts']);
  });

  gulp.task('default', ['watch', 'coffeescripts']);

  gulp.task('done', (function() {}));

}).call(this);

//# sourceMappingURL=gulpfile.js.map
