// Generated by CoffeeScript 1.10.0
(function() {
  var assert, should;

  should = require('should');

  assert = require('assert');

  describe('Configuration', function() {
    return it('configures the application correctly.', function(done) {
      var config, ref, sslOptions;
      process.env.KEY = "KEY";
      process.env.CERT = "CERT";
      process.env.CA = "CA";
      ref = require('../config'), config = ref[0], sslOptions = ref[1];
      config.env.should.be.equal('local');
      return done();
    });
  });

}).call(this);

//# sourceMappingURL=test_configuration.js.map
